### ISSUE TITLE
Automerge is broken for the whole CI line

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/deployments-k8s#2304]
## Description
`ridedott/merge-me-action` was updated and so now it is failing with the following error:
```
Run ridedott/merge-me-action@master
  with:
    GITHUB_LOGIN: nsmbot
    ENABLED_FOR_MANUAL_CHANGES: true
    GITHUB_TOKEN: ***
    MAXIMUM_RETRIES: 25
    ENABLE_GITHUB_API_PREVIEW: false
    MERGE_METHOD: SQUASH
Automatic merges enabled for GitHub login: nsmbot.
Error: An unexpected error occurred: Cannot read property 'endCursor' of undefined, TypeError: Cannot read property 'endCursor' of undefined
    at makeGraphqlIterator (/home/runner/work/_actions/ridedott/merge-me-action/master/webpack:/@ridedott/merge-me-action/src/common/makeGraphqlIterator.ts:50:1)
    at process.node (internal/process/task_queues.js:93:5)
    at branchProtectionRules (/home/runner/work/_actions/ridedott/merge-me-action/master/webpack:/@ridedott/merge-me-action/src/common/listBranchProtectionRules.ts:50:1)
    at continuousIntegrationEndHandle (/home/runner/work/_actions/ridedott/merge-me-action/master/webpack:/@ridedott/merge-me-action/src/eventHandlers/continuousIntegrationEnd/index.ts:80:1).
```

### Issue in `ridedott/merge-me-action`
Here is the issue filed in `ridedott/merge-me-action` - https://github.com/ridedott/merge-me-action/issues/1008, hope they will fix it in the closest future.

### Temporary decrease using version
This issue was introduced by https://github.com/ridedott/merge-me-action/commit/172fa69938b047a51d518d2e7f38b8c1eb3ca583, so it is presented in `master` and last release (`v2.9.0`), but we can switch to using `v.2.8.47` in all our workflow files until it would be fixed.

**Comment by Bolodya1997** [comment]
Looks like this issue was fixed from their side, just need to restart the CI line and check it.
